/*
 * Copyright (c) 2019, WeTeam Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cn.lakex.framework.core.exception;

/**
 * Levels of exception log.
 *
 * @author LarryKoo (larrykoo@126.com)
 * @slogon 站在巨人的肩膀上
 * @date 2019/10/21 16:34
 * @since 3.0.0
 */
public enum ExceptionLevel {
    /**
     * unknown level for default
     */
    UNKNOWN,
    /**
     * Fatal is the highest form of log available, use it for unrecoverable issues.
     */
    FATAL,
    /**
     * Error denotes an unexpected behaviour that prevented the code to work properly.
     */
    ERROR,
    /**
     * Warning should be used to define logs generated by expected and handled bad behaviour.
     */
    WARNING,
    /**
     * Info is used to give general details on the running application, usually only messages.
     */
    INFO,
    /**
     * Debug information to track every detail of the application execution process.
     */
    DEBUG,
    /**
     * Message info, if set this level, don't print exception stack logs.
     */
    MESSAGE;
}
